#!/bin/bash

set -e

FILE_SINFUMAR=~/.sinfumar
ORIGEN_SINFUMAR="24/10/2016"

function main() {
    displaySinFumar && 
    mensajeSinFumar
}

function displaySinFumar() {
    test ! -f $FILE_SINFUMAR ||
    test `diasSinMensaje` -ge 1
}

function diasSinMensaje() {
    diasEntre `creacionArchivoSinFumar` `timestampHoy`
}

function creacionArchivoSinFumar() {
    stat -f %c $FILE_SINFUMAR
}

function timestampHoy() {
    date +%s
}

function diasEntre() {
    echo $(( (((($2 - $1 ) / 60 ) / 60) / 24) ))
}

function mensajeSinFumar() {
    echo "DIAS SIN FUMAR --> $(cantDiasSinFumar)"
    pausarDisplay
    marcarMensajeSinFumar
}

function pausarDisplay() {
    echo -n "Enter para continuar . . ."
    read -s n
    echo
}

function cantDiasSinFumar() {
    diasEntre `timestampSinFumarOrigen` `timestampHoy`
}

function timestampSinFumarOrigen() {
    date -j -f "%d/%m/%Y" "$ORIGEN_SINFUMAR" +%s
}

function marcarMensajeSinFumar() {
    test -f $FILE_SINFUMAR && 
    rm $FILE_SINFUMAR
    
    touch $FILE_SINFUMAR
}

main
